export const DB_GET_INSTALLATIONS = "DB_GET_INSTALLATIONS";
export const DB_INSTALLATIONS_DATA = "DB_INSTALLATIONS_DATA";
export const DB_ADD_INSTALLATION = "DB_ADD_INSTALLATION";

export const SETTINGS_CHANGE = "SETTINGS_CHANGE";

export const SYNC_OVERWRITE_SERVER = "SYNC_OVERWRITE_SERVER";
export const SYNC_OVERWRITE_LOCAL = "SYNC_OVERWRITE_LOCAL";
export const SYNC_SYNCHRONIZE = "SYNC_SYNCHRONIZE";
