export const SETTINGS_CHANGE = "SETTINGS_CHANGE";

export const SYNC_OVERWRITE_SERVER = "SYNC_OVERWRITE_SERVER";
export const SYNC_OVERWRITE_LOCAL = "SYNC_OVERWRITE_LOCAL";
export const SYNC_SYNCHRONIZE = "SYNC_SYNCHRONIZE";
