// SETTINGS
export const SETTINGS_SET_SINGLE = "SETTINGS_SET_SINGLE";
export const SETTINGS_NULLIFY_SINGLE = "SETTINGS_NULLIFY_SINGLE";
export const SETTINGS_POPULATION_COMPLETE = "SETTINGS_POPULATION_COMPLETE";
